# ----------------------------
# Makefile Options
# ----------------------------

NAME = Fruitty
ICON = icon.png
DESCRIPTION = "My first TI84 Game"
COMPRESSED = zx0

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
